# Generated by Django 4.1.4 on 2023-02-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_post_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated']},
        ),
    ]
